---
abstract: 'A module for getting and setting values on a ZyXEL IES5xxx device'
author:
  - 'Jesper Dalberg <jdalberg@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-ZyXEL-IES
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: 0
  Moose: 0
  Net::SNMP::Util: 0
  SNMP: 0
  Test::More: 0
  namespace::autoclean: 0
version: 0.10
